<?php

/**
 * @file
 * Contains predis module hooks.
 */

/**
 * Implements hook_help().
 */
function predis_help($path, $arg) {
  switch ($path) {
    case 'help.page.predis':
      $output = 'A wrapper for Predis library';
      return $output;

  }
}

function predis_permissions() {
  return array(
    'predis administration' => array(
      'title' => t('Predis administration'),
      'restrict access' => TRUE,
    ), 
  );
}